name = "TeoriaGrupos"
version = "0.1.0"
defaultTargets = ["teoriagrupos"]

[[lean_lib]]
name = "TeoriaGrupos"

[[lean_exe]]
name = "teoriagrupos"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"